// GENERATED by tools/worldgen.py from tools/cliffs.json - do not edit by hand.
// Change the JSON, then run `python tools/worldgen.py cliff` with GameMaker closed.

// Cliff kit ids are their palette tile index in ts_cliff (0 = unpainted cell). Paint the top of a
// plateau on the "Cliff" layer; obj_cliff draws its edges and wall, and the wall blocks walkers.
global.cliff_count = 2;
global.cliff_names = ["", "forest_cliff", "rock_cliff"];

// base: first tile of the kit's block (3 per row: left cap, middle, right cap).
// Row 0 is the plateau's top edge, row 1 its surface, rows 2.. the face drawn below it.
// rim_*: pixels of drawn edge inside a border cell, which walkers cannot stand on.
global.cliff_kit = array_create(3, undefined);
global.cliff_face_max = 3;  // tallest wall, in cells
global.cliff_kit[1] = { base: 3, face_rows: 2, rim_top: 22, rim_left: 12, rim_right: 14 };
global.cliff_kit[2] = { base: 15, face_rows: 3, rim_top: 2, rim_left: 2, rim_right: 2 };
