// Smooth terrain drawing ("dual grid").
// The hidden "Terrain" tile layer holds one plain palette tile per cell (tiles 1..terrain_count of
// ts_terrain). Each drawn tile is centred on a cell corner and chosen from the terrains of the 4 cells
// that share that corner, using the transition tables in scr_terrain_data (generated by tools/worldgen.py).

#macro TERRAIN_CELL 32

/// @func terrain_at_cell(tilemap, cell_x, cell_y)
/// @desc Terrain id painted in a cell: 0 = unpainted or outside the layer, -1 = not a palette tile.
function terrain_at_cell(_tm, _cx, _cy) {
    if (_cx < 0 or _cy < 0 or _cx >= tilemap_get_width(_tm) or _cy >= tilemap_get_height(_tm)) return 0;
    var _t = tile_get_index(tilemap_get(_tm, _cx, _cy));
    return (_t <= global.terrain_count) ? _t : -1;
}

/// @func terrain_solid_at(x, y)
/// @desc True if the terrain painted under a room position blocks movement (e.g. water).
function terrain_solid_at(_px, _py) {
    if (global.tm_terrain == -1) return false;
    var _t = terrain_at_cell(global.tm_terrain, floor(_px / TERRAIN_CELL), floor(_py / TERRAIN_CELL));
    return _t > 0 and global.terrain_solid[_t];
}

/// @func terrain_draw_view()
/// @desc Draws the terrain visible in the view. With global.world_debug on, marks corners that have
///       no transition art (e.g. grass painted straight against water) with a magenta X.
function terrain_draw_view() {
    var _tm = global.tm_terrain;
    if (_tm == -1) return;

    var _view = world_view_rect();
    var _half = TERRAIN_CELL div 2;
    var _x0 = floor(_view[0] / TERRAIN_CELL);
    var _y0 = floor(_view[1] / TERRAIN_CELL);
    var _x1 = floor((_view[0] + _view[2]) / TERRAIN_CELL) + 1;
    var _y1 = floor((_view[1] + _view[3]) / TERRAIN_CELL) + 1;
    var _bad_corners = [];

    for (var _vy = _y0; _vy <= _y1; _vy++) {
        for (var _vx = _x0; _vx <= _x1; _vx++) {
            var _tl = terrain_at_cell(_tm, _vx - 1, _vy - 1);
            var _tr = terrain_at_cell(_tm, _vx, _vy - 1);
            var _bl = terrain_at_cell(_tm, _vx - 1, _vy);
            var _br = terrain_at_cell(_tm, _vx, _vy);
            var _bad = (_tl == -1 or _tr == -1 or _bl == -1 or _br == -1);
            _tl = max(_tl, 0);
            _tr = max(_tr, 0);
            _bl = max(_bl, 0);
            _br = max(_br, 0);

            // Unpainted corners copy the first painted one
            var _a = _tl;
            if (_a == 0) _a = _tr;
            if (_a == 0) _a = _bl;
            if (_a == 0) _a = _br;
            if (_a == 0) {
                if (_bad and global.world_debug) array_push(_bad_corners, _vx * TERRAIN_CELL, _vy * TERRAIN_CELL);
                continue;
            }
            if (_tl == 0) _tl = _a;
            if (_tr == 0) _tr = _a;
            if (_bl == 0) _bl = _a;
            if (_br == 0) _br = _a;

            // The other terrain at this corner; three or more different terrains have no art
            var _b = _a;
            if (_tr != _a) _b = _tr;
            if (_bl != _a) {
                if (_b != _a and _b != _bl) _bad = true;
                _b = _bl;
            }
            if (_br != _a) {
                if (_b != _a and _b != _br) _bad = true;
                _b = _br;
            }

            var _tile = _a; // a terrain's plain tile has the same index as its id
            if (_b != _a and !_bad) {
                var _pair = global.terrain_pair[_a][_b];
                if (is_struct(_pair)) {
                    var _mask = (_tr == _b) * 2 + (_bl == _b) * 4 + (_br == _b) * 8; // TL is always _a
                    if (_pair.flip) _mask = 15 - _mask;
                    if (global.terrain_missing[_pair.base + _mask]) {
                        _bad = true;
                    } else {
                        _tile = _pair.base + _mask;
                    }
                } else {
                    _bad = true;
                }
            }

            draw_tile(ts_terrain, _tile, 0, _vx * TERRAIN_CELL - _half, _vy * TERRAIN_CELL - _half);
            if (_bad and global.world_debug) array_push(_bad_corners, _vx * TERRAIN_CELL, _vy * TERRAIN_CELL);
        }
    }

    if (array_length(_bad_corners) == 0) return;
    draw_set_colour(c_fuchsia);
    for (var _i = 0; _i < array_length(_bad_corners); _i += 2) {
        var _cx = _bad_corners[_i];
        var _cy = _bad_corners[_i + 1];
        draw_line_width(_cx - 10, _cy - 10, _cx + 10, _cy + 10, 3);
        draw_line_width(_cx - 10, _cy + 10, _cx + 10, _cy - 10, 3);
    }
    draw_set_colour(c_white);
}
