global.terrain_count = 31
global.terrain_names = ["", "village_grass", "village_sand", "village_sand_pale", "village_dirt", "village_mud", "village_water", "village_water_pale", "forest_grass", "forest_sand", "forest_water", "forest_soil", "town_gravel", "town_snow", "desert_sand", "desert_grass", "desert_sandstone", "ice_snow", "ice_water", "shore_grass", "shore_sand", "shore_water", "shore_reef_sand", "shore_reef_floor", "shore_deep_sand", "shore_deep_floor", "shore_ocean", "rock_snow", "rock_earth", "city_pavement", "city_road", "city_grass"]
global.terrain_solid = [false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false]

global.terrain_pair = array_create(32)
for (var _i = 0; _i < 32; _i++) global.terrain_pair[_i] = array_create(32, undefined)
global.terrain_pair[1][2] = { base: 32, flip: false }
global.terrain_pair[2][1] = { base: 32, flip: true }
global.terrain_pair[1][3] = { base: 48, flip: false }
global.terrain_pair[3][1] = { base: 48, flip: true }
global.terrain_pair[1][4] = { base: 64, flip: false }
global.terrain_pair[4][1] = { base: 64, flip: true }
global.terrain_pair[2][6] = { base: 80, flip: false }
global.terrain_pair[6][2] = { base: 80, flip: true }
global.terrain_pair[3][7] = { base: 96, flip: false }
global.terrain_pair[7][3] = { base: 96, flip: true }
global.terrain_pair[4][5] = { base: 112, flip: false }
global.terrain_pair[5][4] = { base: 112, flip: true }
global.terrain_pair[8][9] = { base: 128, flip: false }
global.terrain_pair[9][8] = { base: 128, flip: true }
global.terrain_pair[15][14] = { base: 144, flip: false }
global.terrain_pair[14][15] = { base: 144, flip: true }
global.terrain_pair[16][14] = { base: 160, flip: false }
global.terrain_pair[14][16] = { base: 160, flip: true }
global.terrain_pair[17][18] = { base: 176, flip: false }
global.terrain_pair[18][17] = { base: 176, flip: true }
global.terrain_pair[19][20] = { base: 192, flip: false }
global.terrain_pair[20][19] = { base: 192, flip: true }
global.terrain_pair[20][21] = { base: 208, flip: false }
global.terrain_pair[21][20] = { base: 208, flip: true }
global.terrain_pair[22][23] = { base: 224, flip: false }
global.terrain_pair[23][22] = { base: 224, flip: true }
global.terrain_pair[24][25] = { base: 240, flip: false }
global.terrain_pair[25][24] = { base: 240, flip: true }
global.terrain_pair[1][8] = { base: 256, flip: false }
global.terrain_pair[8][1] = { base: 256, flip: true }
global.terrain_pair[2][9] = { base: 272, flip: false }
global.terrain_pair[9][2] = { base: 272, flip: true }
global.terrain_pair[8][15] = { base: 288, flip: false }
global.terrain_pair[15][8] = { base: 288, flip: true }
global.terrain_pair[1][19] = { base: 304, flip: false }
global.terrain_pair[19][1] = { base: 304, flip: true }
global.terrain_pair[8][4] = { base: 320, flip: false }
global.terrain_pair[4][8] = { base: 320, flip: true }
global.terrain_pair[8][11] = { base: 336, flip: false }
global.terrain_pair[11][8] = { base: 336, flip: true }
global.terrain_pair[8][12] = { base: 352, flip: false }
global.terrain_pair[12][8] = { base: 352, flip: true }
global.terrain_pair[8][13] = { base: 368, flip: false }
global.terrain_pair[13][8] = { base: 368, flip: true }
global.terrain_pair[8][14] = { base: 384, flip: false }
global.terrain_pair[14][8] = { base: 384, flip: true }
global.terrain_pair[8][17] = { base: 400, flip: false }
global.terrain_pair[17][8] = { base: 400, flip: true }
global.terrain_pair[8][19] = { base: 416, flip: false }
global.terrain_pair[19][8] = { base: 416, flip: true }
global.terrain_pair[8][20] = { base: 432, flip: false }
global.terrain_pair[20][8] = { base: 432, flip: true }
global.terrain_pair[8][27] = { base: 448, flip: false }
global.terrain_pair[27][8] = { base: 448, flip: true }
global.terrain_pair[8][28] = { base: 464, flip: false }
global.terrain_pair[28][8] = { base: 464, flip: true }
global.terrain_pair[8][29] = { base: 480, flip: false }
global.terrain_pair[29][8] = { base: 480, flip: true }
global.terrain_pair[8][31] = { base: 496, flip: false }
global.terrain_pair[31][8] = { base: 496, flip: true }
global.terrain_pair[9][12] = { base: 512, flip: false }
global.terrain_pair[12][9] = { base: 512, flip: true }
global.terrain_pair[9][14] = { base: 528, flip: false }
global.terrain_pair[14][9] = { base: 528, flip: true }
global.terrain_pair[9][16] = { base: 544, flip: false }
global.terrain_pair[16][9] = { base: 544, flip: true }
global.terrain_pair[9][20] = { base: 560, flip: false }
global.terrain_pair[20][9] = { base: 560, flip: true }
global.terrain_pair[9][28] = { base: 576, flip: false }
global.terrain_pair[28][9] = { base: 576, flip: true }
global.terrain_pair[9][10] = { base: 592, flip: false }
global.terrain_pair[10][9] = { base: 592, flip: true }
global.terrain_pair[27][17] = { base: 608, flip: false }
global.terrain_pair[17][27] = { base: 608, flip: true }
global.terrain_pair[27][28] = { base: 624, flip: false }
global.terrain_pair[28][27] = { base: 624, flip: true }
global.terrain_pair[1][27] = { base: 640, flip: false }
global.terrain_pair[27][1] = { base: 640, flip: true }
global.terrain_pair[14][28] = { base: 656, flip: false }
global.terrain_pair[28][14] = { base: 656, flip: true }
global.terrain_pair[19][31] = { base: 672, flip: false }
global.terrain_pair[31][19] = { base: 672, flip: true }
global.terrain_pair[29][31] = { base: 688, flip: false }
global.terrain_pair[31][29] = { base: 688, flip: true }
global.terrain_pair[12][13] = { base: 704, flip: false }
global.terrain_pair[13][12] = { base: 704, flip: true }

global.terrain_missing = array_create(720, false)
global.terrain_missing[38] = true
global.terrain_missing[41] = true
global.terrain_missing[54] = true
global.terrain_missing[57] = true
global.terrain_missing[70] = true
global.terrain_missing[73] = true
global.terrain_missing[86] = true
global.terrain_missing[89] = true
global.terrain_missing[102] = true
global.terrain_missing[105] = true
global.terrain_missing[118] = true
global.terrain_missing[121] = true
global.terrain_missing[134] = true
global.terrain_missing[137] = true
global.terrain_missing[150] = true
global.terrain_missing[153] = true
global.terrain_missing[160] = true
global.terrain_missing[166] = true
global.terrain_missing[169] = true
global.terrain_missing[182] = true
global.terrain_missing[185] = true
global.terrain_missing[191] = true
global.terrain_missing[198] = true
global.terrain_missing[201] = true
global.terrain_missing[214] = true
global.terrain_missing[217] = true
global.terrain_missing[223] = true
global.terrain_missing[230] = true
global.terrain_missing[233] = true
global.terrain_missing[239] = true
global.terrain_missing[246] = true
global.terrain_missing[249] = true
global.terrain_missing[255] = true
